server:
  port: 8112

spring:
  application:
    name: mycloud-rabbitmq-consumer2

  # 数据源配置
  datasource:
    primary:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&autoReconnect=true
      username: root
      password: root

      max-active: 100
      min-idle: 10
      initial-size: 20
      max-wait: 10000
      validation-query: SELECT 1
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 20000


  # rabbitMQ
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


# 异步线程池配置
task:
  pool:
    corePoolSize: 8
    maxPoolSize: 10
    keepAliveTime: 200
    queueCapacity: 20
