server:
  port: 8111

spring:
  application:
    name: mycloud-rabbitmq-consumer1

  # 数据源配置
  datasource:
    primary:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&autoReconnect=true
      username: root
      password: root

      max-active: 100
      min-idle: 10
      initial-size: 20
      max-wait: 10000
      validation-query: SELECT 1
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 20000


  # rabbitMQ
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-returns: true
    publisher-confirm-type: correlated
    # 消息重试
    listener:
      simple:
        retry:
          # 开启重试，默认是false
          enabled: true
          # 重试次数,默认为3次
          max-attempts: 5
          # 重试初始间隔时间，毫秒
          initial-interval: 10000
          # 倍数
          multiplier: 1.5
          # 重试最大间隔时间，毫秒
          max-interval: 30000


  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 20
        max-wait: 500
        max-idle: 10
        min-idle: 0
    timeout: 500


# 异步线程池配置
task:
  pool:
    corePoolSize: 8
    maxPoolSize: 10
    keepAliveTime: 200
    queueCapacity: 20
